### ISSUE TITLE
Link to a user's subdomain from messages has 12 encoded "%20" in the link

### ISSUE THREAD

**Issue by ValerieDD** [bdsmlr-development/bdsmlr-updates#9]
In https://bdsmlr.com/messages, click on a user's avatar to bring up messaging for them. When you then hover over the user's name, the link has 12 encoded spaces in it. It always seems to be 12 spaces, regardless of the length of the user's name (at first I thought it might be some kind of padding issue gone awry).

Example: https://gurlycollegeles%20%20%20%20%20%20%20%20%20%20%20%20.bdsmlr.com

The text of the user's name does not have the spaces appended (carefully clicking and dragging to select the text of the username highlights only the name), so the problem is in the link itself.

Extra request - it would be nice if both the avatar and the text version of the name were clickable, like in the Followers list.

**Comment by jenevieveee** [comment]
Inspect element shows 
`
https://alwayshornyannie


            .bdsmlr.com
`
for the link. Three newlines and twelve space between the subusername and the domain.

This appears to be broken on the dash too -- the link is invalid, but since clicking on the blog name on the dash brings out the side view, the error has gone unnoticed.

Best guess is that /messages page was cut-and-pasted from the dash chat window for styling, but /messages doesn't have the code to support the side view.

It goes a bit deeper too. If you look at the request sent through the actual POST, the actual data is

textoutput | "test"
userid | "375641"
avatar | "uploads/blogs/2019/11/229147/avatar/229147-2qHqeadhGE1.jpg"
name | "alwayshornyannie\n\n\n++++++++++++"

The three new lines match, but the we have 12 '+'s instead of 12 ' 's. This is consistent with the POST request to /newmessage2 from the dash.

**Comment by Mack6767** [comment]
Whilst on the topic of inspect within the bdsmlr.com/messages page, the glaring error of 
`GET https://cdn.rawgit.com/yuku-t/jquery-textcomplete/v1.3.4/dist/jquery.textcomplete.js net::ERR_ABORTED 404` 
upon every click of a separate user in the chat list the correct link referenced link should point to 
`https://ghcdn.rawgit.org/t-kenji/trac-autocomplete-provider-plugin/master/tracautocomplete/htdocs/js/jquery.textcomplete.js`
I'm no web developer but that might help.

**Comment by jenevieveee** [comment]
Don't get me wrong, it should be fixed (and tracked as a different issue), but that's non-critical. That only converts things : r o f l : (without the spaces) into :rofl: when you're typing in the chat window. That's pretty near the bottom of wishlist for site fixes,

**Comment by Mack6767** [comment]
@jenevieveee Lol like I said, I'm no web developer, just a network engineer poking at things lol. I've left the site until they fix chat, they made the impossible, possible. They have a non-social social network site.

**Comment by jenevieveee** [comment]
@Mack6767 Good news, chat is working again.

**Comment by Mack6767** [comment]
> @Mack6767 Good news, chat is working again.

It **was** working @jenevieveee , sadly it's not working anymore... and still no update from the owners. YAY!

**Comment by ValerieDD** [comment]
I'm not sure what changed, but now there are 15 spaces in the link, not 12.

**Comment by ValerieDD** [comment]
This now appears to be fixed. Thank you!
